import json

import requests

from settings import *
from gql import Client, gql
from gql.transport.requests import RequestsHTTPTransport



class ZenIssues:
    def __init__(self):

        self.workspaceId = "61f7875ee7297e0016d92028"
        self.transport = RequestsHTTPTransport(
            url=ZENHUB_ENDPOINT,
            verify=True,
            retries=3,
            headers={"Authorization": f"Bearer {ZENHUB_KEY}"}
        )
        self.client = Client(transport=self.transport, fetch_schema_from_transport=True)

    def exec(self, query, params):
        return self.client.execute(gql(query), variable_values=params)

    def get_issue(self, issue_number):
        query = """
            query getIssueInfo($repositoryGhId: Int!, $issueNumber: Int!) {
          issueByInfo(repositoryGhId: $repositoryGhId, issueNumber: $issueNumber) {
            id
            repository {
              id
              ghId
            }
            number
            title
            body
            state
            estimate {
              value
            }
            sprints (first: 10) {
              nodes {
                id
                name
              }
            }
            labels (first: 10) {
              nodes {
                id
                name
                color
              }
            }
          }
        }
                """

        params = {"workspaceId": self.workspaceId, "issueNumber": issue_number, "repositoryGhId": EMMET_BROWN}
        return self.exec(query, params)

    def get_workspace(self):
        query = """
         query getBoardInfoForWorkspace($workspaceId: ID!) {
  workspace(id: $workspaceId) {
    id
    pipelinesConnection(first: 25) {
      nodes {
        id
        name
        issues(first: 100) {
          nodes {
            id
            title
            number
            estimate {
              value
            }
          }
        }
      }
    }
  }
}
                """

        params = {"workspaceId": self.workspaceId}
        return self.exec(query, params)

    def get_swim_lanes(self):
        worspace = self.get_workspace()
        swim_lanes = {}
        for lane in data["workspace"]['pipelinesConnection']['nodes']:
            swim_lanes[node['name']] = lane['issues']['nodes']








if __name__ == '__main__':
    zh = ZenIssues()
    print(zh.get_swim_lanes())

""""
{'workspace': {'id': '61f7875ee7297e0016d92028', 'pipelinesConnection': {'nodes': [
    {'id': 'Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzI1ODEyODE', 'name': 'New Issues', 'issues': {'nodes': [
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU1Ng',
         'title': 'Improvement/Potential Issue: Service/s may require a restart on appliance IP change', 'number': 18,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU1Nw', 'title': 'Improve proxy usage', 'number': 20,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU1OA', 'title': 'Two places to enter proxy settings', 'number': 21,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU1OQ',
                             'title': 'Improvement: Show build hash in skybaseversion/skypatchversion files',
                             'number': 36, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU2MA',
                                                               'title': 'sql scripts used by dbjanitor should be moved to core db and run using dapper',
                                                               'number': 37, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU2MQ',
         'title': 'Appliance Build 1400 statisticaldataprocessor should not appear in service list, or at least not report "gathering/sending" *yet*',
         'number': 60, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU2Mg',
                                           'title': 'Having a valid deployed configuration is needed for software upgrade to work (and calendar test)',
                                           'number': 65, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU2Mw',
         'title': 'Batch import of room and video systems, that include tags etc.... i.e. appliance to appliance',
         'number': 69, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU2NA', 'title': 'Pexip connection may give out false positive. ',
         'number': 88, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU2NQ', 'title': 'FC:Replace Websocket with SIP.JS', 'number': 134,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU2Ng', 'title': 'FC:Refactor javascript for joining Teams ',
         'number': 135, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU2Nw', 'title': 'FC:Security & Licensing', 'number': 138,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU2OA',
                             'title': 'FC: Screen capture using rendering of screen instead of grabbing video tag',
                             'number': 146, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU3MA', 'title': 'CDR Database', 'number': 154, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU3Mg', 'title': 'Graph api: use places instead of room lists',
         'number': 163, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU3Mw', 'title': 'FC:Homer integration for Chrome Server',
         'number': 196, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU3NQ',
                                            'title': 'FC: Create zookeeper-janitor-service/functionality (the parts that makes the ZK-development easier)',
                                            'number': 212, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU3Ng', 'title': 'Logging for JSSip', 'number': 222, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU3Nw',
         'title': 'Overview page -> meeting volume -> percentage change disappears', 'number': 223, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU3OA',
         'title': 'Bootstrap editor can expose main DB password in cleartext', 'number': 263, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU4MA',
         'title': 'Randymoss logs fatal error and restarts when there is no rooms and endpoints configured  ',
         'number': 274, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU4MQ', 'title': 'skysetuptool gets stuck after upgrade',
         'number': 299, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU4Mg',
                                            'title': 'Too easy to mistake preview software for a release software',
                                            'number': 313, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU4Mw',
         'title': 'Aplliance Postgres port is closed after patching (because we have added new default ports)',
         'number': 333, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU4NA',
                                            'title': 'Grafana installation files are volatile and we should not include them in repo',
                                            'number': 341, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU4NQ',
         'title': 'Package errors are not shown during upgrade. Upgrade should fail', 'number': 344, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU5MQ',
         'title': 'As a C# developer i want to stay current with our toolset. One way is to Move to .NET 6 (LTS) Or Net 7 ',
         'number': 426, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU5NA',
                                            'title': 'Call rejected by resource manager due to time limit or other legal/correct reasons have no "error message"',
                                            'number': 432, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU5NQ', 'title': 'WebEx API improvements', 'number': 435,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU5Nw',
                             'title': 'Zookeeper: Something looks down but is in reality active', 'number': 442,
                             'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjYwMQ', 'title': 'Sync tenant/contract DB across all datacenters',
         'number': 448, 'estimate': {'value': 13.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjYwMg', 'title': 'Instance Manager: Support for media node sw upgrade',
         'number': 455, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjYwNA', 'title': 'Suite: Preference based URI (Connect, CVI, WebRTC)',
         'number': 458, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjYwNQ', 'title': 'Suite: OBTP for Google WebRTC meeting',
         'number': 459, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjYwNg', 'title': 'Suite: OS Migration', 'number': 460,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjYwNw', 'title': 'Suite: Reduce default windows on calendar sync',
         'number': 461, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjYwOA', 'title': 'probably high cpu load from InspectorGadget',
         'number': 464, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MzIyNw', 'title': 'Connect GA', 'number': 471, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjMyODg1MQ', 'title': 'OS Migration', 'number': 473, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjMzMDUxNg', 'title': 'Personal (Cisco) device', 'number': 477,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjMzMDUyNg', 'title': 'Manual failover of Suite servers', 'number': 478,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjMzMDU5NA',
                             'title': 'Per system priority on connection preferences (CVI, Connect, WebRTC)',
                             'number': 479, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjUzOTg2MA',
                                                                'title': 'Services ephemeral nodes disappears from zookeeper. (takes down the whole CONNECT)',
                                                                'number': 494, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjY0OTM2MQ', 'title': 'Buy through Azure Marketplace', 'number': 496,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjY0OTM5Mw', 'title': 'CRM and Contract - Technology migration',
         'number': 497, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjY1MDMzNA', 'title': 'InstanceManager: Version for GA', 'number': 498,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjY1NDMxNA',
                             'title': 'Port lockdown for SPAPI - Only accessible for the license server', 'number': 499,
                             'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjY2NjUxMA', 'title': 'Re-invite for unsupported resolution (no scaling)',
         'number': 501, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjk5OTAxNg',
                                            'title': 'BubbaBroker to scrape out teams meeting status indicator and log on interval.',
                                            'number': 512, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjk5OTA3NQ',
         'title': 'Iterate all ongoing video tags, and fetch resolution, package, etc statistics down to zookeeper',
         'number': 513, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzAwNzk0MQ', 'title': 'To reduce our Azure bill.  Buy reserved servers',
         'number': 3, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzA5OTU2NA',
                                          'title': 'workout current conversation abstraction in recon/resiprocate to understand where to implement gstreamer',
                                          'number': 8, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzA5OTgyMQ', 'title': 'FIR/NACK support in RTCP', 'number': 12,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzA5OTg1OA', 'title': 'support SIP/RTP over websocket', 'number': 13,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzEwMDM0MQ',
                             'title': "implement support for NAT'ed RTP/SRTP interface into SDP", 'number': 16,
                             'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzEwODg3NA', 'title': 'PoC - Remove Kurento dependency', 'number': 17,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzE3MDE3OQ', 'title': 'Advanced/Extended RTCP support', 'number': 23,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzMxOTk0NA', 'title': 'Connect Janitor should clean RM data', 'number': 523,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzUxMzk0Ng',
                             'title': 'Investigate (and remove) constraint on contractID in tenant DB', 'number': 528,
                             'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzUyODAwNQ', 'title': 'Display Current Calls', 'number': 12,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzY2MjYwMQ', 'title': 'Instance Manager v2', 'number': 16,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzc1NjY4Mg',
                             'title': 'Setting up suite/fightclub towards external database without superuser fails.',
                             'number': 544, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzc1OTYzMQ', 'title': 'Calls not ending?', 'number': 545, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg1NzQ3NQ', 'title': "Finalize Alex's call test app", 'number': 550,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg1OTMxNw',
                             'title': 'IM: Copy Folder From IM to MediaNode as part of create and upgrade process',
                             'number': 18, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg2NjgxNQ', 'title': 'Bug #525 solved', 'number': 552, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg4MjE0Nw', 'title': 'Feature/keycloakconfigtool', 'number': 554,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg4MzgxOQ',
                             'title': 'Harmonize usage of public-ip from cloud prep and network interface file',
                             'number': 556, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg4NDEwMw', 'title': 'config fix', 'number': 20, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzk1ODM2Nw',
         'title': 'Prevent room URIs with different case being entered manually', 'number': 558, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzk1ODM3NA', 'title': 'DonmordgudJobhandler is spammy', 'number': 560,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODAzMjc4Nw',
                             'title': "When the closest PAPI doesn't exist/is down, JOIN should try another PAPI if available",
                             'number': 563, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODAzODczNg', 'title': 'new parser and first commit on profile',
         'number': 21, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODA0MjA3OQ',
                                           'title': 'Remove default references to values that are supposed to be in cloud env. file',
                                           'number': 571, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODA0MjIwOQ', 'title': 'Harmonize on one cloud prep file', 'number': 572,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODA0MjIyMg', 'title': 'Update Dockerfile.centos81', 'number': 573,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODA0MjIzNw', 'title': 'Improve "cooldown"', 'number': 574,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODA0MjI5NA', 'title': 'Improve creation of root certification ',
         'number': 575, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODA0NDE3NA',
                                            'title': "Cleanup: Installed flag, how to handle this when the installer isn't used for install and upgrade",
                                            'number': 576, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODA0ODc0NA', 'title': 'bump minor version', 'number': 579,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODEyODEzOQ', 'title': 'Bandwidth bursts beyond requested bandwidth',
         'number': 580, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODEzMTE4NA', 'title': 'Zookeeper fixes and refactors', 'number': 581,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODEzODM1Mg', 'title': 'Office Managment Deploy', 'number': 582,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE0ODk1OA',
                             'title': 'Keycloak: Change the starting of KC to a systemd aka service', 'number': 586,
                             'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE0OTQxNg', 'title': 'Keycloak: System for upgrading KC', 'number': 587,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE0OTkwOA', 'title': 'Keycloak: Update Keycloak image to latest 16.1.1',
         'number': 589, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE0OTk1Mw',
                                            'title': 'Keycloak: Use postgres as a backend. Important for cloud scenarios.',
                                            'number': 591, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE1NDQ3MA',
         'title': 'after state machine changes. changing config does not trigger restart of donmordgud', 'number': 592,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE1NTMyOA', 'title': 'NullReferenceException in ResourceManager',
         'number': 593, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE1NTk4NA',
                                            'title': 'Keycloak: Root web site. Logo should look and feel more like the others',
                                            'number': 594, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE2NTczMw', 'title': 'Inspectorgadget should fetch public IPs',
         'number': 24, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODI1NTA3OQ', 'title': 'Support Improvements - Launch', 'number': 595,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODI1NTE3NA', 'title': 'PAPI Keepalive', 'number': 596, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODM1MzA1OQ', 'title': 'small feature expansion', 'number': 598,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODM1NTAxMA', 'title': 'Use dnf upgrade instead of distro-sync',
         'number': 599, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODM3MjI3Nw', 'title': 'This code looked weird, some auto-merge issue? ',
         'number': 600, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODQ0MTE1Mw',
                                            'title': 'Donmordgud does not react to STATE-messages through Zookeeper',
                                            'number': 601, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODQ1NDg5NA', 'title': 'implement MigrateToRocky in setuptools',
         'number': 605, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODQ2NzgzNQ', 'title': 'Bugfix/null exception on state through zookeeper',
         'number': 607, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODU0MDY3Nw',
                                            'title': 'Bump simple-get from 3.1.0 to 3.1.1 in /deployment/helheim_components/linux/ROOT/var/db/grafana/plugins/agenty-flowcharting-panel',
                                            'number': 611, 'estimate': None}]}},
    {'id': 'Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzI1ODEyODU', 'name': 'Sprint Backlog', 'issues': {'nodes': [
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU3MQ', 'title': 'FC: OutOfService mode', 'number': 161,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU3OQ',
                             'title': 'Webex configured endpoints incorrectly showing connectivity problems',
                             'number': 265, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU4OA', 'title': 'InstanceManager: Fail to set mediaserver to active',
         'number': 420, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU4OQ',
                                            'title': 'InstanceManager: No to little logs/feedback when running cloud_prep script',
                                            'number': 421, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjYwMw',
         'title': 'Instance Manager: Support for infinite profiles, that can be configured', 'number': 456,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjM0MDc4OQ', 'title': 'Staging is partly broken 💔', 'number': 482,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzAxNjA1NA',
                             'title': 'Connect quality degrades when CVI participant is part of the meeting',
                             'number': 516, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzA5OTY4Ng',
                                                                'title': 'implement single video stream H.264 baseline / G.711 fixed pipeline in gstreamer',
                                                                'number': 9, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzA5OTkzNg', 'title': 'Support SDP re-negotiation', 'number': 15,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzE3MTgzNw', 'title': 'Architecture for future epics', 'number': 24,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzM3NTcwMQ',
                             'title': '"Meeting insert" overwrites a Google Meet meeting that do not contain CVI info/number',
                             'number': 525, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzQyNjIyOA', 'title': 'Change Profile on MediaNodes', 'number': 9,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzQyNjMwOQ', 'title': 'DONMORDGUD Should Accept SET_MAX_CALLS command',
         'number': 526, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzUyODM1MA', 'title': 'Instance Commands', 'number': 15, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzUyOTQxNA',
         'title': 'Resourcemanager capacity issue (reads from DB not ZK)', 'number': 532, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg1NDkxMw', 'title': 'Remove hardcoded references to beta.joingw.com',
         'number': 549, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODY1NjkyMQ', 'title': 'Do not allow to save "bad" configs', 'number': 631,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODc1NjE0MQ', 'title': 'Change background "tune"', 'number': 643,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODc5NTYwOA', 'title': 'Location (longitude latitude) Management',
         'number': 644, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODc5NTg2MQ', 'title': 'Long/Lat of  Connect datacenters', 'number': 645,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODc5NzA5NA', 'title': 'Config kills Join', 'number': 646, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODg1MTU2Nw', 'title': 'SQL query takes an insanely amount of time',
         'number': 650, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODg3MzM0NQ', 'title': "Check connectivity order config isn't of type null",
         'number': 653, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODk5MjkyMA',
                                            'title': "BubbaSIP can not handle sdp's that does not contain info about max-fs",
                                            'number': 665, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODk5NjM3NA',
         'title': 'Apache Zookeeper Common/Default Nodes Accessible Without ACL', 'number': 666, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzOTAxNjIxNw',
         'title': 'Cloud prep script for all servers has to be done correctly, ref. opensearch', 'number': 669,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzOTg2MDA0Nw', 'title': 'Poly systems have webrtc as a valid option',
         'number': 721, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MDUwMjMwOA', 'title': 'Connect on-prem v1', 'number': 742,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MDg3Njc1OQ', 'title': 'QA: Does JOIN use on-prem POP already?',
         'number': 751, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MDg3NzQyOQ', 'title': 'Set up local cluster in Hyper-V', 'number': 753,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MDk2NTcwMQ', 'title': '& to be escaped when it appears in the Subject',
         'number': 760, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTA4OTE3NA', 'title': '4x vulnerabilities on Mantis server', 'number': 773,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTU5NTY3Nw',
                             'title': 'Hal2000: zookeeper client for connecting to zookeeper based on instance manager classes',
                             'number': 42, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTU5NTc4NQ',
                                                               'title': 'HAL2000: Input data for server allocation algorithm ',
                                                               'number': 43, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTU5NTgzMQ', 'title': 'HAL2000: The actual algorithm for server allocation',
         'number': 44, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTcwNjYxMg',
                                           'title': 'Instance Manager: Does not find correct number for next instance',
                                           'number': 45, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTg3MTUyNQ', 'title': 'Communicate new public IP for licensing API',
         'number': 817, 'estimate': {'value': 2.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTkwMjM4NQ',
                                                      'title': 'Kurento experience up to 12 second delay after reuse of Kurento Media Pipeline',
                                                      'number': 59, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjAwNTYzOQ', 'title': 'Instance Manager: Connection to multiple zookeeper',
         'number': 50, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjAwNjA2Ng', 'title': 'Ops Tool: Setup zookeeper for ops', 'number': 51,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjAwNjQ0OQ', 'title': 'HAL2000 running several instances on same server ',
         'number': 52, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjU5MTY2OQ',
                                           'title': 'Adjust call rate based on video system capabilities/offer',
                                           'number': 62, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjYzNzE0Ng', 'title': 'Update nginx', 'number': 845, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjY5OTgyMQ',
         'title': 'Operations setup. Setup zookeeper for operations in Azure', 'number': 65, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjcwMDUwNQ',
         'title': 'HAL: Build and deploy to staging. Document setup/install process in wiki', 'number': 68,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0Mjg5ODA0Nw', 'title': 'Instancemanager and HAL: Get limits from Azure',
         'number': 855, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MzY0OTE1MA', 'title': '#1556 - Support for encrypted keys in nginx',
         'number': 867, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MzY1ODQ2Mg', 'title': 'Instance Manager. Media node it never set to active',
         'number': 72, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MzY1ODY0MQ', 'title': 'Hal: Media server timeout. Missing heartbeat',
         'number': 73, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MzgwMTcxOQ', 'title': 'fixes #72 and more stuff', 'number': 75,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0Mzk4MDg1MA',
                             'title': '\t0001473: Automated email notifications for all meetings not triggering - *Not for VMRs',
                             'number': 886, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NDI5MjIzMA',
                                                                'title': 'moved temp log folder to /var/db/tmp if /var/db folder exists. Exc…',
                                                                'number': 913, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NDM4Njc3OQ',
         'title': 'Presentation sharing from Video System to CONNECT/MS Teams', 'number': 926, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NDYyNTEyOQ', 'title': 'Build new 30.06 for CONNECT on-premise',
         'number': 934, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NDY0MDgxNg',
                                            'title': 'Audio channel not always properly configured/setup in gstreamer',
                                            'number': 940, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTA0NDU4NQ', 'title': 'Adjust bandwith in WebRTC endpoint (kurento)',
         'number': 64, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTA3NzI2Ng',
                                           'title': 'Was not able to stop the bubbabroker container with id',
                                           'number': 65, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTE0MTEzMg',
         'title': ' (To be refactored) Gstreamer application to replace kurento (Team Epic)', 'number': 67,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTkxNzk3NQ', 'title': 'BFCP Architecture - Research and Design',
         'number': 1021, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTkxOTE3Ng', 'title': 'BubbaMedia Architecture', 'number': 1024,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTkyMTQ3NA', 'title': 'Keycloak, amend documentation', 'number': 1025,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjA5Njc5MQ', 'title': 'Setup of lab (DB, MNG, Media)', 'number': 1048,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjA5NzE2OA', 'title': 'Deploy IM and HAL (EU Beta)', 'number': 1050,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjA5NzE4MQ', 'title': 'Deploy IM and HAL (US Beta)', 'number': 1051,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjA5NzE5NA', 'title': 'Deploy IM and HAL (US GA West)', 'number': 1053,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjA5ODQ0Mg', 'title': 'Close: Mantis#1556 Git#867 nginx passphrase',
         'number': 1055, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjM1NzM0OA',
                                             'title': '#1459 - Share detail button in Control not updated with new matching engine',
                                             'number': 1057, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjU5MDgwNA', 'title': 'Documentation/Uranus for upgrade tool',
         'number': 1068, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjU5MDkyMg', 'title': 'Documentation/Uranus for IM and HAL', 'number': 1069,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjcwMDQ0OQ', 'title': 'Research: "Sniffing" BFCP towards existing MCUs',
         'number': 1078, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjcxMzAyNQ',
                                             'title': 'Enable a new default software branch, and restrict this branch to Rocky only',
                                             'number': 3, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjcxNDc3OA', 'title': 'Manage migration', 'number': 4, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTg5ODM1NQ', 'title': '0001647: Quoting changes', 'number': 10,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjE4OTU0MQ',
                             'title': 'Go through current reports and specify which one fits the Connect for Goverment use case, including modifications needed,',
                             'number': 1368, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjE5NjMzOA',
                                                                 'title': '#1605: CONNECT EU PROD/BETA - Poly X50 no sent video - mute/unmute fix it.',
                                                                 'number': 1369, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjE5NjQyOA',
         'title': '#1625: Connect call on USE GA - Video drops mid call', 'number': 1370, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzczNDA5MA', 'title': 'Postgres deadlock detected (Disney)', 'number': 1521,
         'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDM0ODI5Mw',
                                       'title': 'API extension of port interface.  BubbaLauncher, Resource Manager, BubbaProxy',
                                       'number': 1601, 'estimate': {'value': 1.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDQ0NDYxNQ', 'title': 'Grapfana changes nginx config back and forth',
         'number': 122, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDg4NTgzOQ',
                                            'title': "Release branch build number 31.01.4361-BETA.  Join doesn't push OBTP to the endpoint",
                                            'number': 1644, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDg5MjA4Mg',
         'title': 'Setup and configure and document CUCM environment we can use for testing without having to wake up Roger',
         'number': 1648, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTE5NjQzOQ',
                                             'title': '#1743 - Upgrade image for Beta to make it ready for "one container"',
                                             'number': 1694, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTgxNzAyNw', 'title': 'GH issue grooming. Aim to close and clarify.  ',
         'number': 1756, 'estimate': {'value': 5.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTg2Mjc2MA',
                                                       'title': 'Enhance log gathering tool (in config) to handle a cluster. Management servers',
                                                       'number': 1761, 'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTg5NDMxMQ', 'title': 'BFCP code is wiping out skyms_diagnostics.json',
         'number': 150, 'estimate': {'value': 2.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NjA2MzIzNg',
                                                      'title': 'As a connect admin I want to be able to upgrade the Media nodes to latest version',
                                                      'number': 1803, 'estimate': {'value': 8.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NjU3MjU5NQ',
         'title': 'Emmetbrown github action should have code coverage step and print coverage report. (Timeboxed)',
         'number': 1858, 'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NjU5MDU5NA',
                                                       'title': "clean up synergysky logger naming to reduce mundane changes in PR's",
                                                       'number': 1864, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NjczOTEzNQ',
         'title': 'Figure out why  Icinga is reporting Unknown for Azure resource', 'number': 1883, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1Njc1NDk3OQ',
         'title': 'Ronny: Figure out what went wrong with licenses when deploying media nodes.', 'number': 1912,
         'estimate': {'value': 2.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1Njc1NTIzNA',
                                       'title': 'Jenkins: Build screen in RnD Should not show feature branch failures (Only official branches)',
                                       'number': 1913, 'estimate': {'value': 1.0}}]}},
    {'id': 'Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzI1ODEyODY', 'name': 'In Progress', 'issues': {'nodes': [
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU5OA', 'title': 'Set up production ', 'number': 443,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjYwMA', 'title': 'Licenses tagged to a certain deployment',
         'number': 445, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzAwMzI4MQ',
                                            'title': 'Audio from Teams to SIP Client is sometimes not working (From SIP To teams always works)',
                                            'number': 514, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzUyODA0Mw', 'title': 'Config', 'number': 13, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzUyODEwNQ',
         'title': 'Unknown Profile Names should have the machine type from azure appended to profile name',
         'number': 14, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzUzMzYxNg', 'title': 'removing console writes', 'number': 531,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg0Nzg0MA', 'title': 'Release/2022january', 'number': 543,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg0Nzg0Mg', 'title': 'Feature/zktesting', 'number': 547, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE0ODQ2NA', 'title': 'Keycloak: Control integration', 'number': 584,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODE0ODU5OA', 'title': 'Keycloak: Integrate Grafana(Analyze)', 'number': 585,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODI1NDgyNA', 'title': 'Call status in Ops-Grafana', 'number': 26,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODI1NTMwMA', 'title': 'Tenant Dashboard', 'number': 27, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODU1MTQ4Ng', 'title': 'Kurento fails to connect to webrtc client / bubbajs',
         'number': 613, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODU2NTI3Nw', 'title': 'Fast update request  From Gstreamer in Kurento',
         'number': 35, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzODg0Mzk3Ng', 'title': 'PoC - Initial buy with order saved in our DB',
         'number': 648, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MDk2NTU5OQ', 'title': 'OBTP Policy', 'number': 759, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MDk2OTUwNg', 'title': '[License portal] New hosting center in azure',
         'number': 762, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTA3NzI3NA',
                                            'title': 'Connect: DMG to check if license is Gateway provider',
                                            'number': 771, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTc3NTM0Nw', 'title': 'Hbr/feature/bubbalauncher to csharp', 'number': 812,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTc3OTkwMQ', 'title': 'OBTP Policy', 'number': 813, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTg5OTI0Nw', 'title': 'Test of Kurento parameters', 'number': 58,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTkxOTMzOA', 'title': 'Cluster Upgrader', 'number': 822, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTkxOTU0OQ', 'title': 'Appliance Updater improvements', 'number': 823,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTkxOTcyOQ', 'title': 'Donmordgud to have "upgrading" state', 'number': 824,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTkyMjEzOA', 'title': 'Refactor/implement ZooKeeper operatians-receipts',
         'number': 825, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjQwNzQ0OA', 'title': 'Instance manager: download/read cloudprep log',
         'number': 55, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjQ2NDc3OA', 'title': 'Hal2000: Make sure algorithm is configurable',
         'number': 58, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjgxNzQ5Mw', 'title': '#1519 - Disney: Slow control', 'number': 852,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MzY0MjkxNA',
                             'title': 'HAL: Check instance manager to see machines being created or deleted (Qued machines)',
                             'number': 865, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MzY1NzczNA', 'title': '#1553 Multiple Endpoints connected to single Room',
         'number': 870, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NDA4OTA5OQ',
                                            'title': 'IM: Increase visiblity if create machine fails (or other exceptions)',
                                            'number': 891, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NDYzMzY3OA', 'title': 'Upgrade Zookeeper', 'number': 939, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NDc5NjEwNQ',
         'title': '.Net 6/7 migration: Replace uHttpSharp with Kestrel ', 'number': 944, 'estimate': {'value': 8.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTE0MDg2NA',
         'title': 'Replace Kurento classes in recon server(Not worked on)', 'number': 66, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTI2Mzc4Mg', 'title': 'Support for lower resolutions', 'number': 972,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTI2MzgwMQ',
                             'title': 'No media channels - synchronization issues on start/connect', 'number': 973,
                             'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTI2MzgyNA', 'title': 'Frozen video just after connection', 'number': 974,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTI2MzgzNw', 'title': 'Audio one way (video system do not receive)',
         'number': 975, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTU5Nzg5NQ',
                                            'title': '#1586 - AES 128 on DX80 incurs packet loss in CONNECT',
                                            'number': 1008, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTY0NzM1Mw',
         'title': 'Address book (from config) lookup when using the dial-out feature in Control', 'number': 1012,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjA5NzE4OQ', 'title': 'Deploy IM and HAL (US GA East)', 'number': 1052,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjA5NzIwMA', 'title': 'Deploy IM and HAL (EU GA)', 'number': 1054,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjY5NjQ0MQ', 'title': 'Setup CUCM in Oslo', 'number': 1076,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjY5NjQ1OQ', 'title': 'Support for CUCM in security/encryption mode',
         'number': 1077, 'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjcwMTI4OA', 'title': 'BFCP PoC "app"', 'number': 1079, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjcxMjc1Nw',
         'title': '#1603 - Only one room gets its OBTP removed when a meeting with multiple rooms are canceled',
         'number': 1083, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjkwNDk0NA', 'title': 'Connect on Prem: Replace postman for spapi on prem',
         'number': 1104, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTYyNjQxNA',
                                             'title': ' interpipe rewrite / refactoring forwarders to support interpipe for WEBRTC',
                                             'number': 78, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc3MzY5Mg', 'title': 'Make a plan for testing group', 'number': 1314,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc3NzM1NA',
                             'title': 'Analyze parameters with sql does not work when moving to grafana 9',
                             'number': 1315, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTk4MjcyNA', 'title': 'unit tests for C# project in CI (Github actions)',
         'number': 1344, 'estimate': {'value': 2.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjE3Mzg1NQ',
                                                       'title': '#1642 - Connect No receive video on Poly 310 Group Series (SRTP/Encryption)',
                                                       'number': 1364, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjMyOTY5NA', 'title': '1. Unit/integration test workshop for C#',
         'number': 1383, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1Mjk5NzA4Mw',
                                             'title': 'Appliance Extracts just part of Fully qualified domain name (FQDN) ',
                                             'number': 1445, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzA4ODE3NA', 'title': 'Hotfix/v31.00.hotfix01', 'number': 1459,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzE2MTQ0Mw',
                             'title': '[Media Server] dialing twice in a row from the same endpoint causes a crash ',
                             'number': 1466, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzE2NjUyMw',
                                                                 'title': 'Wrong license option is used for CONNECT/SUITE-decision',
                                                                 'number': 1467, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzI3OTUyNQ', 'title': '[Media Server] Poly devices support', 'number': 66,
         'estimate': {'value': 8.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzM4Mzc1MQ', 'title': 'Lots of license records created incorrectly',
         'number': 17, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzUxNjA3Mw', 'title': 'Mk/analyzepdfback # 1459', 'number': 1498,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzU5NDg4Mg', 'title': '[new media server] Support for empty invite',
         'number': 93, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDA5MzM3NA', 'title': 'Define architecture', 'number': 1561,
         'estimate': {'value': 2.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDI2NzYwOA',
                                       'title': 'srtpenc0 spits out error code 10, pipeline stops working and reconserver crashes',
                                       'number': 112, 'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDM0ODM0MA', 'title': 'Container POC', 'number': 1602, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDg5NDczMw',
         'title': 'skyrtprewrite: Rewrite timestamps and sequence numbers to avoid having to renegotiate the webrtc side of the call. Hopefully fixes #112',
         'number': 123, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDk3ODI2Mw', 'title': 'Create integration tests for ResourceManager',
         'number': 1658, 'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTAwMDE5Ng',
                                                       'title': '[env] upgrade Azure media node failed: unable to pull dir:/var/db/apps/synergysky_bubbabroker/build_ssky_bubbabroker.fedora-run.tar',
                                                       'number': 1665, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTA2MTU5NA',
         'title': '[Single Container] filtering first invite message and waiting with starting a broker service in single container',
         'number': 1677, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTEzMTg0Mg', 'title': 'Use Polly retry policy in webexcommands',
         'number': 1691, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTE0MjI3MA',
                                             'title': 'version 31.02.4460/31.02.4475  "Espen\'s fix" , presentation sharing via Webex registered endpoint has a lot of package loss. ',
                                             'number': 129, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTI5MDIyNQ',
         'title': 'Onecontainer to rule them. Get end to end call to work on azure dev environment', 'number': 1701,
         'estimate': {'value': 5.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTU2MjIzNw',
                                       'title': 'As a user I want to share my screen using bubbagateway architecture.',
                                       'number': 1719, 'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTU3MDU1MA', 'title': 'Leaking SRTP keys in logs', 'number': 138,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NjA1NTU3NQ',
                             'title': 'Jenkins: appliance_cloud BubbaSIP | BubbaProxy | BubbaGateway were not triggered',
                             'number': 1788, 'estimate': {'value': 0.5}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NjExNjk4Ng',
         'title': 'We need functionality to check wether a stream description matches the stream we already have or has changed in some way.',
         'number': 161, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NjQ5MDExOA',
                                            'title': 'Upgrade bubbasip and bubbaproxy with newest code from resiprocate repository',
                                            'number': 1847, 'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1Njk4MTkwMQ', 'title': 'Remove multi-call support', 'number': 175,
         'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NzA3NzIzNw', 'title': 'New teams browser client - Need hotfixing',
         'number': 1953, 'estimate': {'value': 8.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NzA4NDY4MA',
                                                       'title': '[TESTS] add support for both teams client DOM versions',
                                                       'number': 56, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NzExOTM4Ng',
         'title': 'As a developer I want to have information about all communication between resiprocate and the media server in the diagnostics log',
         'number': 180, 'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NzEyNTAxOA',
                                                      'title': 'Add JSONRPC requests, responses and events to diagnostics and diagnostics UI',
                                                      'number': 181, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NzEzMDU1Mw', 'title': 'OBTP improvements', 'number': 1957,
         'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NzIxMjcyNw',
                                       'title': 'Prototype basic stats monitoring and bandwidth management mechanism',
                                       'number': 193, 'estimate': {'value': 8.0}}]}},
    {'id': 'Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzI3NDM2NzM', 'name': 'Test/QA', 'issues': {'nodes': [
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjMzMDQ5Nw',
         'title': '#1484 - CSV Bulk import. Poly endpoints imported as Cisco CE endpoints', 'number': 476,
         'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzOTg5OTYwMQ', 'title': 'SW for upgrades based on what OS Suite is running',
         'number': 2, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTM2NTkyOA',
                                          'title': "As a Admin of the license/contract tool I want to be able to set 'none' as beta/preview version",
                                          'number': 982, 'estimate': {'value': 2.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTY0Njk1Mw',
         'title': 'When using the green "dial-in" button in Control, I want the endpoint to dial it\'s assign CONNECT URI, if it exist',
         'number': 1010, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjY4NDQzNg',
                                             'title': 'Document what cryptographical modules we currently are using (Connect and Suite)',
                                             'number': 1070, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0Njg5ODgzNA', 'title': '#1606 OBTP Policy not working', 'number': 103,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0ODExMTM4Nw', 'title': 'Harden HAL (re-subsribe)', 'number': 105,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTY2MTc1MQ',
                             'title': 'Analyze: Grafana fails on datasource upgrade for some reports', 'number': 1299,
                             'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTg5ODI3OA', 'title': '0001648: Change hubspot API keys to private apps',
         'number': 8, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjQ5NjA4MA',
                                          'title': 'Improve status check that currently use 16sec. (sql optimization)',
                                          'number': 1401, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTI5NDU1NQ',
         'title': 'Control service  hangs when asked to stop politely by donmordgud', 'number': 1702,
         'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTgyNjY5MQ', 'title': 'SIP renegotiation support (Poly related)',
         'number': 149, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NTkwNjU0OQ',
                                            'title': '0001741: EWS Emulator providing meetings in the wrong order',
                                            'number': 1771, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NjAwNjM2MA', 'title': 'media: SIPRTP Renegotiation support', 'number': 155,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NjU5ODIxNg', 'title': '#1767 - Quotations in meeting title crashes OBTP',
         'number': 1867, 'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NzAxMTUzNQ',
                                                       'title': '[TESTS]: setup framework for manual test reports/issues',
                                                       'number': 55, 'estimate': None}]}},
    {'id': 'Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzI4NTI1MDI', 'name': 'Done', 'issues': {'nodes': [
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU4Ng',
         'title': 'Video system should not show OBTP when being auto-dialed through the booking macro', 'number': 385,
         'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNjI3MjU5MA', 'title': 'CUCM Support (SIP empty invites)', 'number': 424,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzA5OTcyNA',
                             'title': 'implement support for dynamic codec selection based on prefered in SDP',
                             'number': 10, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzA5OTc1MQ',
                                                               'title': 'implement support SRTP/Encryption support with gstreamer',
                                                               'number': 11, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg1MzU3MQ', 'title': '(Connect) Server upgrades', 'number': 548,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzIzNzg4Mzk4OQ', 'title': 'Multiple (odd) cloud management servers',
         'number': 557, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MTMyOTQ2Mw',
                                            'title': '(!!due 30. June) Validate that our media-nodes / image has the new root certificate for MS-Teams',
                                            'number': 788, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MjM3NjM0OA', 'title': 'Connect servers: CONNECT licensing revalidate',
         'number': 836, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0MzY0OTE3NQ', 'title': 'Upgrade Grafana and plugins to latest version',
         'number': 868, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTI2MjI4MQ', 'title': '#1496 - PDF reports in Analyze/Grafana',
         'number': 970, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTY0NzE5MA',
                                            'title': '(Replaced with auto dial out macro) Autoconnect upon meeting start - [#1568] [G&D]',
                                            'number': 1011, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTkxODEzNw',
         'title': 'Presentation sharing Binary Floor Control Protocol (BFCP) service/app ', 'number': 1022,
         'estimate': {'value': 8.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NTkxODE2Mw',
                                       'title': 'Chromium/Teams Client - Scraping and emulation of sharing',
                                       'number': 1023, 'estimate': {'value': 8.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjU2ODU3OA',
         'title': 'Add IP to poly endpoints in config tool so that they can be accessed via CONTROL GUI #1597 #1604',
         'number': 1067, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjY5NjM0MQ', 'title': 'CUCM Parity', 'number': 1075, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NjkwMzI4OA', 'title': 'Connect on prem: Configtool, show state',
         'number': 1103, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NzI1ODQ2OQ', 'title': 'Easy launch to video system from Suite - [Eckert]',
         'number': 1129, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0NzYzOTI0Nw', 'title': 'Connect splash screen', 'number': 1146,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0ODIzNzgyNQ',
                             'title': 'As an end-user i want to see platform specific icons on my touch panel, reflecting the meeting (platform) that I am about to join',
                             'number': 1171, 'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0ODYwODU0Mg',
         'title': 'I want participants to show up with their display name when joining Teams meeting through Connect',
         'number': 1178, 'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0OTUxMDI5MA',
                                                       'title': 'MS Teams control and interaction through Cisco Webex Room Navigator (touch panel) ',
                                                       'number': 1194, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0OTU1MDA2MA', 'title': 'CACI', 'number': 1195, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI0OTg1NTI5Mw',
         'title': 'As an admin I do not want to be given the option to turn "Track People Count" on, when the endpoint do not support this feature/sensor',
         'number': 1199, 'estimate': {'value': 2.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MDEwNDIxOQ',
                                                       'title': 'As a white glove admin I want Suite to be able to dial out x minutes prior to the meeting start, so that the meeting can start on time [Foley]',
                                                       'number': 1205, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MDkzNTgxMQ',
         'title': 'Simplify Connect-mgmt  server setup. Auto create root-certificate for NGINX ', 'number': 1247,
         'estimate': {'value': 2.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTAyODk3NQ', 'title': 'configure video endpoints', 'number': 21,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTE0ODEzMA', 'title': 'Suite macro management ', 'number': 1261,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTE1OTc2MA',
                             'title': 'Teams Panel User Story 1: As an end user I would like to see a roster list with all meeting participants, in order to get an overview of all participants.',
                             'number': 1266, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTIwOTg0MQ',
                                                                 'title': 'Extend endpoint logistics API for proxying communication between macro and connect cloud (PAPI) (Henrik/Ronny)',
                                                                 'number': 1270, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTM4NzY0Mg', 'title': 'License Move proxy to Azure', 'number': 1280,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTYyMzA4MA', 'title': 'Add a separated jenkinsFile and Jenkins pipeline',
         'number': 1292, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTYyNzMwNw', 'title': 'Add second video stream to new media server',
         'number': 1297, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTY2MTg0NA',
                                             'title': 'Quality/Testing: As developers we see the need to increase Quality',
                                             'number': 1300, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTY3MjIwOA',
         'title': 'Teams Panel User Story 2: As an end user I would like to see status for participants',
         'number': 1301, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTY3MjQzMg',
                                             'title': 'Teams Panel User Story 3: As an end user I would like to raise hand/lower hand in teams meeting from touch panel and show current status',
                                             'number': 1302, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc1NzA4MQ', 'title': 'Keycloak - last mile for release', 'number': 1304,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc1OTg3MQ',
                             'title': 'As an end user I want to see additional information on the roster list, in order to get a better understanding of the meeting and its participants',
                             'number': 1306, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc1OTg4Mw',
                                                                 'title': 'As an end user I want to interact with the roster list to get a better experience, I want to "fit-to-frame" for each individual participant. Fit-to-frame experience is defined by MS',
                                                                 'number': 1307, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc1OTg5Nw',
         'title': 'As an end user I want to interact with the roster list to get a better experience, I want to pin each individual participant. Pin experience is defined by MS',
         'number': 1308, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc1OTkwNA',
                                             'title': 'As an end user I want to interact with meeting to get a better experience, I want to toggle layout, where the possible layouts are defined by MS, as per their meeting platform capabilities.',
                                             'number': 1309, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc1OTkyMg',
         'title': 'As an end user I want to interact with meeting to get a better experience, I want to raise and lower hand for my own participant (i.e. the room I am in). Raise/lower hand is defined as per the capability within the MS platform.',
         'number': 1310, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc2MTY0Ng',
                                             'title': 'As a Control user I want to be able with one click to launch a new browser tab that links directly to the Poly touch interface. This from the expanded meeting view where the various rooms are listed. This will help me to easier manage the video systems',
                                             'number': 1311, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTc2MTY1NQ',
         'title': 'As a Config user I want to be able with one click to launch a new browser tab that links to any video system (using its configure IP or FQDN), from the "video system" config tab/area',
         'number': 1312, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTg0MDY2OQ',
                                             'title': '\t0001667: Upgrade Connect Beta with version 1 of Teams Roster list functionality',
                                             'number': 1320, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTg5ODE3Ng', 'title': '0001649: License server UI Performance issues',
         'number': 6, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MTkwMjc0Nw', 'title': 'HC cleaner for co-existence', 'number': 1333,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjAwODA3NQ',
                             'title': 'Teams Panel User Story 1: roster list DX70 failed in SYNERGY_SKY_ConnectControlMacro_v1',
                             'number': 1347, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjEyNzkzMw', 'title': '#1631 - OBTP thread creates deadlock',
         'number': 1355, 'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjE5Njk4Nw',
                                                       'title': "#1620: Matchingengine: Google meet meeting with pexip SIP interop not correctly matched [Can't extract correct SIP from french invite]",
                                                       'number': 1372, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjE5NzEzNQ',
         'title': '#1609: VMR Calendar Email Address counting towards total rooms', 'number': 1373,
         'estimate': {'value': 1.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjE5NzQyMQ',
                                       'title': '#1636: After enabling In-Room booking the Endpointlogistics.service has an error that constantly loops and service restarts',
                                       'number': 1374, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjIyMzMxMA', 'title': 'Split Licensing API', 'number': 11,
         'estimate': {'value': 5.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjI3NTQ5Nw',
                                       'title': 'I want the "recording has started" banner to be automatically dismissed after 10 seconds, so it doesn\'t stay visible on the screen',
                                       'number': 1380, 'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjI4ODk2OA',
         'title': 'I want the "5 minutes left inyour meeting" banner to be automatically dismissed after 15 seconds, so it doesn\'t stay visible on the screen',
         'number': 1381, 'estimate': {'value': 1.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjQwMjcxNg',
                                                       'title': 'As a user I want to insert SIP URIs into a room calendar so Hybrid Calendar can pick it up correctly, and provide OBTP to the video systems',
                                                       'number': 1392, 'estimate': {'value': 13.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjQ5NjA2Mg',
         'title': '#1693 - Config for license mechanism do not work for Connect for Government', 'number': 1399,
         'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjQ5NjA3Mw',
                                       'title': 'Reduce Webex API "hammering" by changing the endpoint status checker to make 1 call for all data, rather than multiple small',
                                       'number': 1400, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjQ5NjA5Mw',
         'title': 'Improve heavy query in OBTP thread, that searches for meetings for the next 24h', 'number': 1402,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjUyOTY4NQ',
                             'title': 'Unable to create logfile on medianode using SSH menu Mantis 1694',
                             'number': 1411, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjU5NjEzOA',
                                                                 'title': 'To help diagnose customer local DB issues Adding postgressl.conf to full logbundle',
                                                                 'number': 1425, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjkwNTA5OA',
         'title': 'To increase perfomance enable autoprepare Postgres connection string', 'number': 1440,
         'estimate': {'value': 5.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MjkxMTcyNw',
                                       'title': 'Connect. Nodes that are upgraded using pipeline and appliance updater can get stuck in idle.',
                                       'number': 1441, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzA1NzUzNg', 'title': 'Kurentoenv file missing', 'number': 1449,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzA1NzYwNw',
                             'title': 'DB Perf. Reduce load.  Bifrost sync Materialized Views  less data, and improve Query against job table',
                             'number': 1451, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzExNDk1OA', 'title': 'Build new Suite with Teams macro', 'number': 1461,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzExNTI0Nw', 'title': '#1705: Sorting for booking API', 'number': 1462,
         'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzEzNzM3OA', 'title': 'Machinename=>Hostname with domaininfo',
         'number': 117, 'estimate': {'value': 2.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzE2MTQyNw',
                                                      'title': '[Media Server]: poly endpoints (Studio X30 and Group300) dialing crash',
                                                      'number': 1465, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzE3NTE1NQ',
         'title': '#1697: license validation wipes CONNECT On-Prem Integration settings', 'number': 1469,
         'estimate': {'value': 1.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzE4MTQxOA',
                                       'title': "#1592: Matchingengine: Don't fully update meeting assets after booking change from Onetimevmr to Teams meeting",
                                       'number': 1470, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzE4MTQ1Nw',
         'title': '#1699: Duplicate meetings in meeting history in Analyze', 'number': 1471, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzE4MTkyOA', 'title': '#1702: Matchingengine: French urldefense',
         'number': 1472, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzE4MjU2Mw', 'title': '#1548: Super long meetings in Control',
         'number': 1474, 'estimate': {'value': 5.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzE4NDg3Mw',
                                                       'title': '#1700: Matchingengine: dot not extracted as part of prefix ',
                                                       'number': 1477, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzI3OTUzNA',
         'title': 'Separate unit test complexity levels in github actions (Run tests nightly)', 'number': 75,
         'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzMyNjU3OA',
                                       'title': '[new media server] C20 Cisco Endpoint is not able to connect properly due to incorrect audio codec',
                                       'number': 80, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzM5NzY5MA',
                                                                         'title': "Document branching and organize meeting about it and how to do PR's",
                                                                         'number': 1482, 'estimate': {'value': 2.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzM5ODQ3Ng',
         'title': 'Setup Azure Environment for Development. Increase stability of QA environment and remove block for development testing. ',
         'number': 1483, 'estimate': {'value': 2.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzQ2NDEyNQ', 'title': '[new media server]: version 31.00.4158 issues ',
         'number': 81, 'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzQ2NDU5NQ',
                                           'title': '[new media server] presentation sharing Dx70 has bad resolution (as it uses the main video stream for presentation)',
                                           'number': 84, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzUzOTMzMw',
         'title': 'Make HubSpot version default to V3 and remove old code', 'number': 18, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzY3NzIyNw',
         'title': 'ADMIN should be able setup SUITE+CONNECT with a shared license and database', 'number': 1513,
         'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzczMDA1NQ', 'title': 'ERR log with little guidance on what is wrong',
         'number': 1515, 'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzczMDA2OQ',
                                                       'title': 'DBG log messages that follow an ERR log should be printed regardless of debug being enabled',
                                                       'number': 1516, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzczMjIwNQ',
         'title': "Calendar sync causes Exception with 'Object reference not set ...' (Disney)", 'number': 1518,
         'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzczMjMzNQ',
                                       'title': 'Log room/video system info when we fail to set httpfeedback register',
                                       'number': 1519, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzczNDAyOA', 'title': 'CONTROL tries to access non-existing table (Disney)',
         'number': 1520, 'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1Mzc0NDQ3NA',
                                                       'title': 'Error logs need to show what room/endpoint they are related to',
                                                       'number': 1522, 'estimate': {'value': 3.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1Mzc5MDExOA', 'title': 'Remove unwanted licenses', 'number': 19,
         'estimate': None}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1Mzg4NzA5Mg',
                             'title': 'Prevent high cost in Azure because of wrong provisioning. ', 'number': 1534,
                             'estimate': {'value': 2.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1Mzg4NzI2NQ',
                                                           'title': 'Detect failure in our automatic provisioning at an earlier by time raising an alert in Icinga',
                                                           'number': 1535, 'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1Mzg5NTU2OA',
         'title': 'Matching of Skype for Sandia Labs does not have any URI', 'number': 1537,
         'estimate': {'value': 2.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1MzkwMzY3NQ',
                                       'title': 'Bug: HAL/IM does not stop creating resources when we hit a limit.  ',
                                       'number': 1540, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDA5MTUzOA', 'title': 'Describe all services Timeboxed to one day',
         'number': 1558, 'estimate': {'value': 3.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDA5MjY1OA',
                                                       'title': 'As Synergy SKY I want to be able to sell (Connect) directly to a customer',
                                                       'number': 21, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDE3NjEyNg',
         'title': 'Update list of 3rd party libraries we use [Before Nov.]', 'number': 1570,
         'estimate': {'value': 5.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDE3NjI0OQ', 'title': 'Create a standard sales contract', 'number': 23,
         'estimate': {'value': 8.0}},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDE3NjI2Ng', 'title': 'Create new "Offer"mechanism in quoting tool',
         'number': 24, 'estimate': {'value': 8.0}}, {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDE3NjkwNA',
                                                     'title': 'Stabilize call handling; One container to rule them all',
                                                     'number': 1572, 'estimate': None},
        {'id': 'Z2lkOi8vcmFwdG9yL0lzc3VlLzI1NDE4Njc1MA',
         'title': 'Icinga. Go trough current warnings and see what can be fixed', 'number': 1574,
         'estimate': {'value': 2.0}}]}}]}}}
"""